name: release-please

on:
  push:
    branches:
      - main
<<<<<<< Updated upstream
=======
      - "[0-9]-[0-9]-[0-9]"
>>>>>>> Stashed changes

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          target-branch: "${{GITHUB_REF_NAME}}"
